if UnitClass("player") ~= "Paladin" then return end

SLASH_IDPSPALADIN1 = "/idps"
function SlashCmdList.IDPSPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:CancelPlayerBuff("Righteous Fury")
	IWin:DevotionAura()
	IWin:RetributionAura()
	IWin:ConcentrationAura()
	IWin:ShadowResistanceAura()
	IWin:FrostResistanceAura()
	IWin:FireResistanceAura()
	IWin:SanctityAura()
	IWin:BlessingOfSanctuary()
	IWin:BlessingOfWisdom()
	IWin:BlessingOfMight()
	IWin:BlessingOfKings()
	IWin:BlessingOfLight()
	IWin:BlessingOfSalvation()
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(10)
	IWin:SealOfRighteousness(10)
	IWin:HammerOfWrath(30)
	IWin:ExorcismRanged(30)
	IWin:JudgementReact()
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyStrikeHolyMight(IWin_Settings["GCD"])
	IWin:CrusaderStrike(15,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:RepentanceRaid()
	IWin:ConsecrationFocus(90)
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_ICLEAVEPALADIN1 = "/icleave"
function SlashCmdList.ICLEAVEPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:CancelPlayerBuff("Righteous Fury")
	IWin:DevotionAura()
	IWin:RetributionAura()
	IWin:ConcentrationAura()
	IWin:ShadowResistanceAura()
	IWin:FrostResistanceAura()
	IWin:FireResistanceAura()
	IWin:SanctityAura()
	IWin:BlessingOfSanctuary()
	IWin:BlessingOfWisdom()
	IWin:BlessingOfMight()
	IWin:BlessingOfKings()
	IWin:BlessingOfLight()
	IWin:BlessingOfSalvation()
	IWin:HolyShield(5,0)
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(15)
	IWin:SealOfRighteousness(15)
	IWin:JudgementReact()
	IWin:Consecration(25)
	IWin:HolyWrath(25)
	IWin:JudgementRanged(50,IWin_Settings["GCD"])
	IWin:CrusaderStrike(15,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Judgement(50,IWin_Settings["GCD"])
	IWin:RepentanceRaid()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_ITANKPALADIN1 = "/itank"
function SlashCmdList.ITANKPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:CancelSalvation()
	IWin:RighteousFury()
	IWin:DevotionAura()
	IWin:RetributionAura()
	IWin:ConcentrationAura()
	IWin:ShadowResistanceAura()
	IWin:FrostResistanceAura()
	IWin:FireResistanceAura()
	IWin:SanctityAura()
	IWin:BlessingOfSanctuary()
	IWin:BlessingOfWisdom()
	IWin:BlessingOfMight()
	IWin:BlessingOfKings()
	IWin:BlessingOfLight()
	IWin:BlessingOfSalvation()
	IWin:HolyShockPull(20)
	IWin:HolyShield(5,3)
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(15)
	IWin:SealOfRighteousness(15)
	IWin:ExorcismRanged(30)
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:HolyShock(15)
	IWin:ConsecrationFocus(70)
	IWin:RepentanceRaid()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_IHODORPALADIN1 = "/ihodor"
function SlashCmdList.IHODORPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:CancelSalvation()
	IWin:RighteousFury()
	IWin:DevotionAura()
	IWin:RetributionAura()
	IWin:ConcentrationAura()
	IWin:ShadowResistanceAura()
	IWin:FrostResistanceAura()
	IWin:FireResistanceAura()
	IWin:SanctityAura()
	IWin:BlessingOfSanctuary()
	IWin:BlessingOfWisdom()
	IWin:BlessingOfMight()
	IWin:BlessingOfKings()
	IWin:BlessingOfLight()
	IWin:BlessingOfSalvation()
	IWin:Consecration(25)
	IWin:HolyShockPull(20)
	IWin:HolyShield(5,0)
	IWin:HolyShock(15)
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfWisdomEco()
	IWin:ExorcismRanged(30)
	IWin:JudgementRanged(50,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:Judgement(50,IWin_Settings["GCD"])
	IWin:RepentanceRaid()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_IECOPALADIN1 = "/ieco"
function SlashCmdList.IECOPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:DevotionAura()
	IWin:RetributionAura()
	IWin:ConcentrationAura()
	IWin:ShadowResistanceAura()
	IWin:FrostResistanceAura()
	IWin:FireResistanceAura()
	IWin:SanctityAura()
	IWin:BlessingOfSanctuary()
	IWin:BlessingOfWisdom()
	IWin:BlessingOfMight()
	IWin:BlessingOfKings()
	IWin:BlessingOfLight()
	IWin:BlessingOfSalvation()
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfWisdomEco()
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyShield(5,3)
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:HolyShock(15)
	IWin:StartAttack()
end

SLASH_IJUDGEPALADIN1 = "/ijudge"
function SlashCmdList.IJUDGEPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(15)
	IWin:SealOfRighteousness(15)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:StartAttack()
end

SLASH_ICHASEPALADIN1 = "/ichase"
function SlashCmdList.ICHASEPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HandOfFreedom()
	IWin:SealOfJustice()
	IWin:JudgementReact()
	IWin:Cleanse()
	IWin:Purify()
	IWin:StartAttack()
end

SLASH_ISTUNPALADIN1 = "/istun"
function SlashCmdList.ISTUNPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HammerOfJustice()
	IWin:StartAttack()
	IWin:Repentance()
end

SLASH_ITAUNTPALADIN1 = "/itaunt"
function SlashCmdList.ITAUNTPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HandOfReckoning()
	IWin:StartAttack()
end

SLASH_IBUBBLEHEARTHPALADIN1 = "/ibubblehearth"
function SlashCmdList.IBUBBLEHEARTHPALADIN()
	IWin:InitializeRotation()
	IWin:DivineShield()
	IWin:UseItem("Hearthstone")
end