if UnitClass("player") ~= "Warrior" then return end

SLASH_IDPSWARRIOR1 = "/idps"
function SlashCmdList.IDPSWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:DPSStance()
	IWin:Bloodrage()
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmorDPSRefresh()
	IWin:SunderArmorElite()
	IWin:DPSStanceDefault()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Execute()
	IWin:SetReservedRageExecute()
	IWin:HamstringJousting()
	IWin:Slam()
	IWin:SetReservedRageSlam()
	IWin:SetSlamQueued()
	IWin:Execute2Hander()
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:Whirlwind(IWin_Settings["GCD"])
	IWin:SetReservedRage("Whirlwind", "cooldown")
	IWin:Overpower()
	IWin:MasterStrike()
	IWin:SetReservedRageMasterStrike()
	IWin:ConcussionBlow()
	IWin:BattleShoutRefresh()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:Rend()
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:BerserkerRage()
	IWin:HeroicStrike()
	IWin:SetReservedRage("Heroic Strike", "nocooldown")
	IWin:Perception()
	IWin:MasterStrikeWindfury()
	IWin:SetReservedRageMasterStrikeWindfury()
	IWin:PummelWindfury()
	IWin:SetReservedRagePummelWindfury()
	IWin:HamstringWindfury()
	IWin:SetReservedRageHamstringWindfury()
	IWin:SunderArmorWindfury()
	IWin:SetReservedRageSunderArmorWindfury()
	IWin:StartAttack()
end

SLASH_ICLEAVEWARRIOR1 = "/icleave"
function SlashCmdList.ICLEAVEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:SunderArmorDPSRefresh()
	IWin:CleaveStance()
	IWin:Bloodrage()
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SweepingStrikes()
	IWin:SetReservedRage("Sweeping Strikes", "cooldown")
	IWin:WhirlwindAOE(IWin_Settings["GCD"])
	IWin:SetReservedRage("Whirlwind", "cooldown")
	IWin:SunderArmorElite()
	IWin:DPSStanceDefault()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Slam()
	IWin:SetReservedRageSlam()
	IWin:SetSlamQueued()
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:Overpower()
	IWin:ConcussionBlow()
	IWin:ThunderClapDPS()
	IWin:BattleShoutRefresh()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:BerserkerRage()
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:Cleave()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_ITANKWARRIOR1 = "/itank"
function SlashCmdList.ITANKWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:CancelSalvation()
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:Bloodrage()
	IWin:ShieldBlock()
	IWin:SlamThreat()
	IWin:SetReservedRageSlamThreat()
	IWin:SetSlamQueuedThreat()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:OverpowerDefensiveTactics()
	IWin:SunderArmorFirstStack()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRage("Bloodthirst", "cooldown")
	IWin:Revenge()
	IWin:SetReservedRageRevenge()
	IWin:BattleShoutRefresh()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:HeroicStrikeTank()
	IWin:ConcussionBlow()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_IHODORWARRIOR1 = "/ihodor"
function SlashCmdList.IHODORWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:CancelSalvation()
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:Bloodrage()
	IWin:ShieldBlockFRD()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:OverpowerDefensiveTactics()
	IWin:SunderArmorFirstStack()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:ConcussionBlow()
	IWin:ThunderClap(IWin_Settings["GCD"])
	IWin:SetReservedRage("Thunder Clap", "cooldown")
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:BattleShoutRefresh()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:CleaveAOE()
	IWin:Perception()
	IWin:StartAttack()
end

SLASH_ICHASEWARRIOR1 = "/ichase"
function SlashCmdList.ICHASEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Charge()
	IWin:Intervene()
	IWin:Intercept()
	IWin:Hamstring()
	IWin:PiercingHowl()
	IWin:StartAttack()
end

SLASH_IKICKWARRIOR1 = "/ikick"
function SlashCmdList.IKICKWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:ShieldBash()
	IWin:Pummel()
	IWin:StartAttack()
end

SLASH_IFEARDANCEWARRIOR1 = "/ifeardance"
function SlashCmdList.IFEARDANCEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:BerserkerRageImmune()
	IWin:StartAttack()
end

SLASH_ITAUNTWARRIOR1 = "/itaunt"
function SlashCmdList.ITAUNTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Taunt()
	IWin:MockingBlow()
	IWin:StartAttack()
end

SLASH_ISHOOTWARRIOR1 = "/ishoot"
function SlashCmdList.ISHOOTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Shoot()
end